import { BaseData, Friend } from "./types";

export const types: BaseData[] = [
  { id: 1, name: "Buio" },
  { id: 2, name: "Lotta" },
  { id: 3, name: "Roccia" },
  { id: 4, name: "Volante" },
  { id: 5, name: "Erba" },
  { id: 6, name: "Normale" },
  { id: 7, name: "Psico" },
];

export const generations: BaseData[] = [
  { id: 1, name: "Prima generazione (1994)" },
  { id: 2, name: "Seconda generazione (1995)" },
  { id: 3, name: "Terza generazione (1996)" },
  { id: 4, name: "Quarta generazione (1997)" },
  { id: 5, name: "Quinta generazione (1998)" },
  { id: 6, name: "Fossile (< 1994)" },
  { id: 7, name: "Futuristico (> 1998)" },
];

export const hairs: BaseData[] = [
  { id: 1, name: "Capelli biondi" },
  { id: 2, name: "Capelli castani" },
  { id: 3, name: "Capelli neri" },
  { id: 4, name: "Capelli rossi" },
];

export const beards: BaseData[] = [
  { id: 1, name: "Ha la barba" },
  { id: 2, name: "Non ha la barba" },
];

export const houses: BaseData[] = [
  { id: 1, name: "Ha una casa propria" },
  { id: 2, name: "Non ha una casa propria" },
];

export const engagements: BaseData[] = [
  { id: 1, name: "Fidanzat*" },
  { id: 2, name: "Non fidanzat*" },
];

export const friends: Friend[] = [
  {
    id: 1,
    name: "Irene",
    type1: 5,
    type2: 6,
    generation: 4,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 2,
    name: "Mirco",
    type1: 1,
    type2: 7,
    generation: 1,
    hair: 2,
    beard: 1,
    house: 2,
    engagement: 1,
  },
  {
    id: 3,
    name: "Paul",
    type1: 2,
    type2: 3,
    generation: 5,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 4,
    name: "Beps",
    type1: 3,
    type2: 4,
    generation: 2,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 5,
    name: "Viga",
    type1: 3,
    type2: 7,
    generation: 2,
    hair: 2,
    beard: 2,
    house: 1,
    engagement: 2,
  },
  {
    id: 6,
    name: "Cava",
    type1: 6,
    type2: 7,
    generation: 1,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 7,
    name: "Mazi",
    type1: 1,
    type2: 2,
    generation: 1,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 8,
    name: "Boss",
    type1: 1,
    type2: 5,
    generation: 1,
    hair: 3,
    beard: 1,
    house: 1,
    engagement: 1,
  },
  {
    id: 9,
    name: "Quod",
    type1: 3,
    type2: 4,
    generation: 3,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 10,
    name: "Dago",
    type1: 2,
    type2: 3,
    generation: 5,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 11,
    name: "Waldo",
    type1: 1,
    type2: 2,
    generation: 2,
    hair: 3,
    beard: 2,
    house: 1,
    engagement: 2,
  },
  {
    id: 12,
    name: "Vero",
    type1: 3,
    type2: 5,
    generation: 3,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 13,
    name: "Sara",
    type1: 5,
    type2: 7,
    generation: 3,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 14,
    name: "Giuli",
    type1: 6,
    type2: 7,
    generation: 3,
    hair: 1,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 15,
    name: "Marti",
    type1: 6,
    type2: 7,
    generation: 1,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 16,
    name: "Noe",
    type1: 4,
    type2: 7,
    generation: 2,
    hair: 2,
    beard: 2,
    house: 1,
    engagement: 1,
  },
  {
    id: 17,
    name: "Max",
    type1: 6,
    type2: 2,
    generation: 4,
    hair: 3,
    beard: 1,
    house: 2,
    engagement: 2,
  },
  {
    id: 18,
    name: "Freank",
    type1: 1,
    type2: 5,
    generation: 3,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 19,
    name: "Michi",
    type1: 3,
    type2: 5,
    generation: 4,
    hair: 1,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 19,
    name: "Sem",
    type1: 5,
    type2: 6,
    generation: 3,
    hair: 1,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 21,
    name: "Claudia",
    type1: 1,
    type2: 6,
    generation: 4,
    hair: 1,
    beard: 2,
    house: 2,
    engagement: 2,
  },
];
