import { Attribute, Friend, Variant } from "./types";

const friendAttributes: Attribute[] = [
  { id: 1, name: "type1", model: "types" },
  { id: 2, name: "type2", model: "types" },
  { id: 3, name: "generation", model: "generations" },
  { id: 4, name: "hair", model: "hairs" },
  { id: 5, name: "beard", model: "beards" },
  { id: 6, name: "house", model: "houses" },
  { id: 7, name: "engagement", model: "engagements" },
];

const types: Variant[] = [
  { id: 1, name: "Buio" },
  { id: 2, name: "Lotta" },
  { id: 3, name: "Roccia" },
  { id: 4, name: "Volante" },
  { id: 5, name: "Erba" },
  { id: 6, name: "Normale" },
  { id: 7, name: "Psico" },
];

const generations: Variant[] = [
  { id: 1, name: "Prima generazione (1994)" },
  { id: 2, name: "Seconda generazione (1995)" },
  { id: 3, name: "Terza generazione (1996)" },
  { id: 4, name: "Quarta generazione (1997)" },
  { id: 5, name: "Quinta generazione (1998)" },
  { id: 6, name: "Fossile (< 1994)" },
  { id: 7, name: "Futuristico (> 1998)" },
];

const hairs: Variant[] = [
  { id: 1, name: "Capelli biondi" },
  { id: 2, name: "Capelli castani" },
  { id: 3, name: "Capelli neri" },
  { id: 4, name: "Capelli rossi" },
];

const beards: Variant[] = [
  { id: 1, name: "Ha la barba" },
  { id: 2, name: "Non ha la barba" },
];

const houses: Variant[] = [
  { id: 1, name: "Ha una casa propria" },
  { id: 2, name: "Non ha una casa propria" },
];

const engagements: Variant[] = [
  { id: 1, name: "Fidanzat*" },
  { id: 2, name: "Non fidanzat*" },
];

const friends: Friend[] = [
  {
    id: 1,
    name: "Irene",
    type1: 5,
    type2: 6,
    generation: 4,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 2,
    name: "Mirco",
    type1: 1,
    type2: 7,
    generation: 1,
    hair: 2,
    beard: 1,
    house: 2,
    engagement: 1,
  },
  {
    id: 3,
    name: "Paul",
    type1: 2,
    type2: 3,
    generation: 5,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 4,
    name: "Beps",
    type1: 3,
    type2: 4,
    generation: 2,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 5,
    name: "Viga",
    type1: 3,
    type2: 7,
    generation: 2,
    hair: 2,
    beard: 2,
    house: 1,
    engagement: 2,
  },
  {
    id: 6,
    name: "Cava",
    type1: 6,
    type2: 7,
    generation: 1,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 7,
    name: "Mazi",
    type1: 1,
    type2: 2,
    generation: 1,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 8,
    name: "Boss",
    type1: 1,
    type2: 5,
    generation: 1,
    hair: 3,
    beard: 1,
    house: 1,
    engagement: 1,
  },
  {
    id: 9,
    name: "Quod",
    type1: 3,
    type2: 4,
    generation: 3,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 10,
    name: "Dago",
    type1: 2,
    type2: 3,
    generation: 5,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 11,
    name: "Waldo",
    type1: 1,
    type2: 2,
    generation: 2,
    hair: 3,
    beard: 2,
    house: 1,
    engagement: 2,
  },
  {
    id: 12,
    name: "Vero",
    type1: 3,
    type2: 5,
    generation: 3,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 13,
    name: "Sara",
    type1: 5,
    type2: 7,
    generation: 3,
    hair: 3,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 14,
    name: "Giuli",
    type1: 6,
    type2: 7,
    generation: 3,
    hair: 1,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 15,
    name: "Marti",
    type1: 6,
    type2: 7,
    generation: 1,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 16,
    name: "Noe",
    type1: 4,
    type2: 7,
    generation: 2,
    hair: 2,
    beard: 2,
    house: 1,
    engagement: 1,
  },
  {
    id: 17,
    name: "Max",
    type1: 6,
    type2: 2,
    generation: 4,
    hair: 3,
    beard: 1,
    house: 2,
    engagement: 2,
  },
  {
    id: 18,
    name: "Freank",
    type1: 1,
    type2: 5,
    generation: 3,
    hair: 2,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 19,
    name: "Michi",
    type1: 3,
    type2: 5,
    generation: 4,
    hair: 1,
    beard: 2,
    house: 2,
    engagement: 1,
  },
  {
    id: 19,
    name: "Sem",
    type1: 5,
    type2: 6,
    generation: 3,
    hair: 1,
    beard: 2,
    house: 2,
    engagement: 2,
  },
  {
    id: 21,
    name: "Claudia",
    type1: 1,
    type2: 6,
    generation: 4,
    hair: 1,
    beard: 2,
    house: 2,
    engagement: 2,
  },
];

export default {
  friendAttributes,
  types,
  generations,
  hairs,
  beards,
  houses,
  engagements,
  friends,
};
