import { Attribute, Variant, Friend } from "./types";

// Data
const friendAttributes: Attribute[] = [
  { id: 1, name: "gender", model: "genders" },
  { id: 2, name: "hair", model: "hairs" },
  { id: 3, name: "location", model: "locations" },
  { id: 4, name: "degree", model: "degrees" },
  { id: 5, name: "curriculum", model: "curricula" },
  { id: 6, name: "zanco", model: "zanco" },
  { id: 7, name: "origin", model: "origins" },
  { id: 8, name: "pep", model: "peps" },
];

const genders: Variant[] = [
  { id: 1, name: "Femmina" },
  { id: 2, name: "Maschio" },
];

const hairs: Variant[] = [
  { id: 1, name: "Capelli biondi" },
  { id: 2, name: "Capelli castani" },
  { id: 3, name: "Capelli neri" },
];

const degrees: Variant[] = [
  { id: 1, name: "Triennale in Mate" },
  { id: 2, name: "Magistrale in Mate" },
  { id: 3, name: "Dottorato in Mate" },
  { id: 4, name: "Non laureat* in Mate" },
];

const locations: Variant[] = [
  { id: 1, name: "Vive in Italia" },
  { id: 2, name: "Vive in Europa (non UE)" },
  { id: 3, name: "Vive in Europa (UE, non Italia)" },
  { id: 4, name: "Vive in paese extra-europeo" },
];

const curricula: Variant[] = [
  { id: 1, name: "Curriculum generale" },
  { id: 2, name: "Curriculum applicativo" },
  { id: 3, name: "Non ha frequentato in magistrale" },
];

const zanco: Variant[] = [
  { id: 1, name: "Ha dato un esame con Zanco" },
  { id: 2, name: "Non ha dato esami con Zanco" },
];

const origins: Variant[] = [
  { id: 1, name: "Origine milanese" },
  { id: 2, name: "Origine brianzola" },
  { id: 3, name: "Origine comasca" },
  { id: 4, name: "Origine bergamasca" },
  { id: 5, name: "Origine bresciana" },
  { id: 6, name: "Origine padania sud" },
  { id: 7, name: "Origine extra-lombarda" },
];

const peps: Variant[] = [
  { id: 1, name: "E' stato candidat* di Lista ideale" },
  { id: 2, name: "E' stato candidat* di Obiettivo studenti" },
  {
    id: 3,
    name: "Non espost* politicamente (non candidat* in lista di ateneo)",
  },
];

// const erasmus =

const friends: Friend[] = [
  {
    id: 1,
    name: "Francesca Guffanti",
    gender: 1,
    hair: 2,
    location: 4,
    degree: 3,
    curriculum: 1,
    zanco: 1,
    origin: 3,
    pep: 3,
  },
  {
    id: 2,
    name: "Andrea Cappelletti",
    gender: 2,
    hair: 3,
    location: 1,
    degree: 3,
    curriculum: 1,
    zanco: 1,
    origin: 1,
    pep: 1,
  },
  {
    id: 3,
    name: "Nicola Daprà",
    gender: 2,
    hair: 3,
    location: 1,
    degree: 2,
    curriculum: 1,
    zanco: 1,
    origin: 1,
    pep: 3,
  },
  {
    id: 4,
    name: "Alessandro Landoni",
    gender: 2,
    hair: 2,
    location: 1,
    degree: 2,
    curriculum: 2,
    zanco: 1,
    origin: 3,
    pep: 1,
  },
  {
    id: 5,
    name: "Leonardo Fiore",
    gender: 2,
    hair: 3,
    location: 1,
    degree: 2,
    curriculum: 1,
    zanco: 1,
    origin: 1,
    pep: 3,
  },
  {
    id: 6,
    name: "Mirco De Pascale",
    gender: 2,
    hair: 2,
    location: 1,
    degree: 2,
    curriculum: 1,
    zanco: 1,
    origin: 2,
    pep: 3,
  },
  {
    id: 7,
    name: "Camilla Feroldi",
    gender: 1,
    hair: 2,
    location: 1,
    degree: 2,
    curriculum: 2,
    zanco: 2,
    origin: 1,
    pep: 3,
  },
  {
    id: 8,
    name: "Paola Lamperti",
    gender: 1,
    hair: 1,
    location: 2,
    degree: 2,
    curriculum: 2,
    zanco: 2,
    origin: 5,
    pep: 3,
  },
  {
    id: 9,
    name: "Federico Girotti",
    gender: 2,
    hair: 1,
    location: 1,
    degree: 3,
    curriculum: 1,
    zanco: 1,
    origin: 1,
    pep: 3,
  },
  {
    id: 10,
    name: "Lorenzo Zambon",
    gender: 2,
    hair: 3,
    location: 2,
    degree: 3,
    curriculum: 1,
    zanco: 1,
    origin: 1,
    pep: 3,
  },
  {
    id: 11,
    name: "Stefano Decio",
    gender: 2,
    hair: 3,
    location: 4,
    degree: 3,
    curriculum: 1,
    zanco: 1,
    origin: 1,
    pep: 1,
  },
  {
    id: 12,
    name: "Stefano Nicoli",
    gender: 2,
    hair: 3,
    location: 2,
    degree: 2,
    curriculum: 2,
    zanco: 1,
    origin: 4,
    pep: 3,
  },
  {
    id: 13,
    name: "Gabriele Lobbia",
    gender: 2,
    hair: 3,
    location: 3,
    degree: 3,
    curriculum: 1,
    zanco: 1,
    origin: 1,
    pep: 3,
  },
  {
    id: 14,
    name: "Greta Coraglia",
    gender: 1,
    hair: 2,
    location: 1,
    degree: 3,
    curriculum: 1,
    zanco: 1,
    origin: 1,
    pep: 3,
  },
  {
    id: 15,
    name: "Ludovico Marini",
    gender: 2,
    hair: 2,
    location: 4,
    degree: 3,
    curriculum: 1,
    zanco: 1,
    origin: 1,
    pep: 3,
  },
  {
    id: 16,
    name: "Giacomo Allaria",
    gender: 2,
    hair: 1,
    location: 1,
    degree: 2,
    curriculum: 2,
    zanco: 1,
    origin: 1,
    pep: 3,
  },
  {
    id: 17,
    name: "Chiara Magnani",
    gender: 1,
    hair: 3,
    location: 1,
    degree: 2,
    curriculum: 2,
    zanco: 2,
    origin: 1,
    pep: 3,
  },
  {
    id: 18,
    name: "Claudio Agostini",
    gender: 2,
    hair: 1,
    location: 3,
    degree: 3,
    curriculum: 1,
    zanco: 1,
    origin: 2,
    pep: 1,
  },
  {
    id: 19,
    name: "Noemi Chignoli",
    gender: 1,
    hair: 2,
    location: 1,
    degree: 2,
    curriculum: 2,
    zanco: 2,
    origin: 1,
    pep: 3,
  },
  {
    id: 19,
    name: "Luca Frittoli",
    gender: 2,
    hair: 1,
    location: 1,
    degree: 3,
    curriculum: 2,
    zanco: 1,
    origin: 2,
    pep: 3,
  },
  {
    id: 21,
    name: "Andrea Zanatta",
    gender: 2,
    hair: 3,
    location: 1,
    degree: 4,
    curriculum: 3,
    zanco: 2,
    origin: 6,
    pep: 3,
  },
  {
    id: 22,
    name: "Sofia Guarato",
    gender: 1,
    hair: 2,
    location: 1,
    degree: 4,
    curriculum: 3,
    zanco: 2,
    origin: 1,
    pep: 3,
  },
  {
    id: 23,
    name: "Elisabetta Peviani",
    gender: 1,
    hair: 2,
    location: 1,
    degree: 4,
    curriculum: 3,
    zanco: 2,
    origin: 6,
    pep: 3,
  },
  {
    id: 24,
    name: "Agostina Ferrari",
    gender: 1,
    hair: 2,
    location: 1,
    degree: 4,
    curriculum: 3,
    zanco: 2,
    origin: 6,
    pep: 3,
  },
];

export default {
  friendAttributes,
  genders,
  hairs,
  locations,
  degrees,
  curricula,
  zanco,
  origins,
  peps,
  friends,
};
